name: CI

on: [push]

jobs:
  validate:
    name: Validate Ontologies and Example Data
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 1
        - name: install jena
          run: make install
        - name: validate everything
          run: make validate
        - name: validate example with check
          run: make validate-example-with-check
